<a href="https://colab.research.google.com/github/emilieyds/aus-regional-income-indicators/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01. Explore ABS Regional Data

This notebook explores the structure of public Australian Bureau of Statistics (ABS) regional datasets used to construct regional income indicators.

Main goals:
1. Load public ABS ASGS and LGA regional datasets
2. Inspect available geography levels
3. Identify income, population, household, and inequality variables
4. Confirm which variables will be used in the income indicator pipeline

In [1]:
import pandas as pd

## 1) Download public ABS regional datasets

In [2]:
ASGS_URL = "https://api.data.abs.gov.au/files/ABS_ABS_REGIONAL_ASGS2021_1.0.0.csv"
LGA_URL = "https://api.data.abs.gov.au/files/ABS_ABS_REGIONAL_LGA2021_1.0.0.csv"

In [3]:
df_asgs = pd.read_csv(ASGS_URL, low_memory=False)
df_lga = pd.read_csv(LGA_URL, low_memory=False)

## 2) Inspect basic structure

In [4]:
print("ASGS dataset shape:", df_asgs.shape)
print("LGA dataset shape:", df_lga.shape)

ASGS dataset shape: (6033462, 24)
LGA dataset shape: (1093239, 24)

In [5]:
df_asgs.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,MEASURE,Data Item,REGIONTYPE,Region Type,ASGS_2021,Region,...,OBS_VALUE,Observation Value,UNIT_MEASURE,Unit of Measure,UNIT_MULT,Unit of Multiplier,OBS_STATUS,Observation Status,OBS_COMMENT,Observation Comment
0,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,AUS,Australia,AUS,Australia,...,24190907.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
1,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,AUS,Australia,AUS,Australia,...,24594202.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
2,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,AUS,Australia,AUS,Australia,...,24966643.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
3,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,AUS,Australia,AUS,Australia,...,25340217.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
4,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,AUS,Australia,AUS,Australia,...,25655289.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_lga.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,MEASURE,Data Item,REGIONTYPE,Region Type,LGA_2021,Region,...,OBS_VALUE,Observation Value,UNIT_MEASURE,Unit of Measure,UNIT_MULT,Unit of Multiplier,OBS_STATUS,Observation Status,OBS_COMMENT,Observation Comment
0,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ADFS_5,Previously served in the Australian Defence Fo...,LGA2021,Local Government Areas (2021),14400,Kiama,...,2.9,NaN,PCT,Percent,NaN,NaN,NaN,NaN,NaN,NaN
1,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ADFS_5,Previously served in the Australian Defence Fo...,LGA2021,Local Government Areas (2021),19399,Unincorporated NSW,...,3.5,NaN,PCT,Percent,NaN,NaN,NaN,NaN,NaN,NaN
2,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,AGEMIG_17,Persons born overseas: 75-79 years,LGA2021,Local Government Areas (2021),14650,Lake Macquarie,...,1286.0,NaN,NUM,Number,NaN,NaN,NaN,NaN,NaN,NaN
3,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,AGEMIG_17,Persons born overseas: 75-79 years,LGA2021,Local Government Areas (2021),14650,Lake Macquarie,...,1688.0,NaN,NUM,Number,NaN,NaN,NaN,NaN,NaN,NaN
4,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,AGEMIG_17,Persons born overseas: 75-79 years,LGA2021,Local Government Areas (2021),16900,Shellharbour,...,885.0,NaN,NUM,Number,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# ASGS Column names
df_asgs.columns.tolist()

['STRUCTURE',
 'STRUCTURE_ID',
 'STRUCTURE_NAME',
 'ACTION',
 'MEASURE',
 'Data Item',
 'REGIONTYPE',
 'Region Type',
 'ASGS_2021',
 'Region',
 'FREQUENCY',
 'Frequency',
 'TIME_PERIOD',
 'Time Period',
 'OBS_VALUE',
 'Observation Value',
 'UNIT_MEASURE',
 'Unit of Measure',
 'UNIT_MULT',
 'Unit of Multiplier',
 'OBS_STATUS',
 'Observation Status',
 'OBS_COMMENT',
 'Observation Comment']

In [8]:
# LGA Column names
df_lga.columns.tolist()

['STRUCTURE',
 'STRUCTURE_ID',
 'STRUCTURE_NAME',
 'ACTION',
 'MEASURE',
 'Data Item',
 'REGIONTYPE',
 'Region Type',
 'LGA_2021',
 'Region',
 'FREQUENCY',
 'Frequency',
 'TIME_PERIOD',
 'Time Period',
 'OBS_VALUE',
 'Observation Value',
 'UNIT_MEASURE',
 'Unit of Measure',
 'UNIT_MULT',
 'Unit of Multiplier',
 'OBS_STATUS',
 'Observation Status',
 'OBS_COMMENT',
 'Observation Comment']

### 2.1) Available geography levels in ASGS and LGA data

In [9]:
# ASGS geography data
asgs_geographies = (
    df_asgs[["REGIONTYPE", "Region Type"]]
    .drop_duplicates()
    .sort_values("REGIONTYPE")
)

asgs_geographies

      REGIONTYPE                             Region Type
0            AUS                               Australia
17146      GCCSA  Greater Capital City Statistical Areas
2634         SA2                Statistical Area Level 2
594          SA3                Statistical Area Level 3
60           SA4                Statistical Area Level 4
6            STE                  States and Territories

In [10]:
# LGA geography data
lga_geographies = (
    df_lga[["REGIONTYPE", "Region Type"]]
    .drop_duplicates()
    .sort_values("REGIONTYPE")
)

lga_geographies

  REGIONTYPE                    Region Type
0    LGA2021  Local Government Areas (2021)

### 2.2) Years available in ASGS and LGA data

In [11]:
# ASGS years
df_asgs["TIME_PERIOD"].drop_duplicates().sort_values().tolist()

[2011, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]

In [12]:
# LGA years
df_lga["TIME_PERIOD"].drop_duplicates().sort_values().tolist()

[2011, 2016, 2017, 2018, 2019, 2020, 2021, 2022]

## 3) Explore available variables

In [13]:
asgs_vars = (
    df_asgs[["MEASURE", "Data Item"]]
    .drop_duplicates()
    .sort_values("MEASURE")
)

asgs_vars.head(20)

           MEASURE                                          Data Item
4877291    ACTIV_2  Persons who have need for assistance with core...
4868920    ACTIV_3  Persons who have need for assistance with core...
2240022     ADFS_2  Currently serving in the Australian Defence Force
2242621     ADFS_3  Previously served in the Australian Defence Force
2245420     ADFS_4  Currently serving in the Australian Defence Fo...
2247938     ADFS_5  Previously served in the Australian Defence Fo...
5568134  AGEMIG_10                 Persons born overseas: 40-44 years
5573698  AGEMIG_11                 Persons born overseas: 45-49 years
5579269  AGEMIG_12                 Persons born overseas: 50-54 years
5584848  AGEMIG_13                 Persons born overseas: 55-59 years
5590428  AGEMIG_14                 Persons born overseas: 60-64 years
5595997  AGEMIG_15                 Persons born overseas: 65-69 years
5601554  AGEMIG_16                 Persons born overseas: 70-74 years
5607083  AGEMIG_17                 Persons born overseas: 75-79 years
5612581  AGEMIG_18                 Persons born overseas: 80-84 years
5618016  AGEMIG_19           Persons born overseas: 85 years and over
5525002   AGEMIG_2                   Persons born overseas: 0-4 years
5529827   AGEMIG_3                   Persons born overseas: 5-9 years
5535143   AGEMIG_4                 Persons born overseas: 10-14 years
5540555   AGEMIG_5                 Persons born overseas: 15-19 years

### 3.1) Search for income-related variables

In [14]:
income_related_vars = asgs_vars[
    asgs_vars["Data Item"].str.contains(
        "income|household|gini|population|employee|investment|equivalised",
        case=False,
        na=False
    )
].sort_values(["MEASURE", "Data Item"])

income_related_vars

          MEASURE                                          Data Item
2011322      BD_5  Standardised death rate (deaths per 1000 stand...
2653473  CABEE_13        Employing business exits with 1-4 employees
2664413  CABEE_14       Employing business exits with 5-19 employees
2542642   CABEE_3            Employing businesses with 1-4 employees
2570829  CABEE_38     Employing businesses with 20 or more employees
...           ...                                                ...
5466182   VEHIC_2                    No motor vehicles per household
5474516   VEHIC_3                    One motor vehicle per household
5482949   VEHIC_4                   Two motor vehicles per household
5491369   VEHIC_5                 Three motor vehicles per household
5499730   VEHIC_6          Four or more motor vehicles per household

[150 rows x 2 columns]

### 3.2) Variables selected for the income indicator pipeline

In [15]:
selected_measures = [
    # Population and households
    "ERP_P_2",      # Persons aged 0-4 years
    "ERP_P_3",      # Persons aged 5-9 years
    "ERP_P_4",      # Persons aged 10-14 years
    "ERP_P_20",     # Estimated resident population
    "HHTYPE_5",     # Total households
    "HHTYPE_6",     # Average household size

    # Income components
    "INCOME_3",     # Total employee income
    "INCOME_6",     # Total own unincorporated business income
    "INCOME_9",     # Total investment income

    # Total income
    "INCOME_19",    # Total income earners
    "INCOME_18",    # Total income
    "INCOME_17",    # Median total income
    "INCOME_36",    # Mean total income

    # Equivalised household income
    "EQUIV_2",      # Median equivalised total household income

    # Inequality
    "INCOME_41",    # Gini coefficient
    "INCOME_37",    # P80/P20 ratio
]

In [16]:
selected_variable_dictionary = asgs_vars[
    asgs_vars["MEASURE"].isin(selected_measures)
].sort_values("MEASURE")

selected_variable_dictionary

           MEASURE                                          Data Item
4345481    EQUIV_2  Median equivalised total household income (wee...
1365999    ERP_P_2                             Persons aged 0-4 years
0         ERP_P_20                      Estimated resident population
1382839    ERP_P_3                             Persons aged 5-9 years
1399678    ERP_P_4                           Persons aged 10-14 years
5049006   HHTYPE_5                                   Total households
5057515   HHTYPE_6            Average household size (no. of persons)
3959016  INCOME_17  Median total income (excl. Government pensions...
3948954  INCOME_18  Total income (excl. Government pensions and al...
3928823  INCOME_19  Total income earners (excl. Government pension...
3710692   INCOME_3                         Total employee income ($m)
3969081  INCOME_36  Mean total income (excl. Government pensions a...
3979147  INCOME_37  Total income (excl. Government pensions and al...
4018423  INCOME_41  Total income (excl. Government pensions and al...
3770706   INCOME_6      Total own unincorporated business income ($m)
3830322   INCOME_9                       Total investment income ($m)

## 4.1) Check whether all selected variables are available in ASGS data

In [17]:
available_measures = set(asgs_vars["MEASURE"])
missing_measures = [m for m in selected_measures if m not in available_measures]

print("Missing selected measures:", missing_measures)

Missing selected measures: []

### 4.1.1) Inspect sample rows for selected variables across key ASGS geographies

In [18]:
sample_asgs = df_asgs[
    (df_asgs["REGIONTYPE"].isin(["AUS", "STE", "SA4", "SA3", "SA2"])) &
    (df_asgs["MEASURE"].isin(selected_measures))
].copy()

sample_asgs.head(20)

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,MEASURE,Data Item,REGIONTYPE,Region Type,ASGS_2021,Region,...,OBS_VALUE,Observation Value,UNIT_MEASURE,Unit of Measure,UNIT_MULT,Unit of Multiplier,OBS_STATUS,Observation Status,OBS_COMMENT,Observation Comment
0,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,AUS,Australia,AUS,Australia,...,24190907.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
1,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,AUS,Australia,AUS,Australia,...,24594202.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
2,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,AUS,Australia,AUS,Australia,...,24966643.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
3,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,AUS,Australia,AUS,Australia,...,25340217.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
4,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,AUS,Australia,AUS,Australia,...,25655289.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
5,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,AUS,Australia,AUS,Australia,...,25688079.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
6,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,STE,States and Territories,1,New South Wales,...,7732858.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
7,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,STE,States and Territories,1,New South Wales,...,7850871.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
8,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,STE,States and Territories,1,New South Wales,...,7945580.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
9,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,STE,States and Territories,1,New South Wales,...,8034305.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
10,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,STE,States and Territories,1,New South Wales,...,8094317.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
11,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,STE,States and Territories,1,New South Wales,...,8093815.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
12,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,STE,States and Territories,2,Victoria,...,6173172.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
13,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,STE,States and Territories,2,Victoria,...,6299798.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
14,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,STE,States and Territories,2,Victoria,...,6418168.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
15,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,STE,States and Territories,2,Victoria,...,6530852.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
16,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,STE,States and Territories,2,Victoria,...,6606149.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
17,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,STE,States and Territories,2,Victoria,...,6548040.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
18,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,STE,States and Territories,3,Queensland,...,4845152.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
19,DATAFLOW,ABS:ABS_REGIONAL_ASGS2021(1.0.0),"Data by region 2011-2022, by ASGS main structu...",I,ERP_P_20,Estimated resident population,STE,States and Territories,3,Queensland,...,4928374.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN

### 4.1.2) Check observations by geography level

In [19]:
obs_by_geography = (
    sample_asgs
    .groupby("REGIONTYPE")
    .size()
    .reset_index(name="n_observations")
    .sort_values("REGIONTYPE")
)

obs_by_geography

  REGIONTYPE  n_observations
0        AUS              69
1        SA2          151918
2        SA3           23203
3        SA4            6105
4        STE             585

### 4.1.3) Inspect SA2 coding structure

In [20]:
sa2_sample = (
    df_asgs[df_asgs["REGIONTYPE"] == "SA2"]
    [["ASGS_2021", "Region"]]
    .drop_duplicates()
    .copy()
)

sa2_sample["ASGS_2021"] = sa2_sample["ASGS_2021"].astype(str).str.zfill(9)

sa2_sample["state_code"] = sa2_sample["ASGS_2021"].str[0]
sa2_sample["sa4_code"] = sa2_sample["ASGS_2021"].str[:3]
sa2_sample["sa3_code"] = sa2_sample["ASGS_2021"].str[:5]
sa2_sample["sa2_code"] = sa2_sample["ASGS_2021"]

sa2_sample.head()

,ASGS_2021,Region,state_code,sa4_code,sa3_code,sa2_code
2634,102011028,Avoca Beach - Copacabana,1,102,10201,102011028
2640,102011029,Box Head - MacMasters Beach,1,102,10201,102011029
2646,102011030,Calga - Kulnura,1,102,10201,102011030
2652,102011031,Erina - Green Point,1,102,10201,102011031
2658,102011032,Gosford - Springfield,1,102,10201,102011032

## 4.2) Inspect LGA selected variables

In [21]:
lga_vars = (
    df_lga[["MEASURE", "Data Item"]]
    .drop_duplicates()
    .sort_values("MEASURE")
)

lga_selected_variable_dictionary = lga_vars[
    lga_vars["MEASURE"].isin(selected_measures)
].sort_values("MEASURE")

lga_selected_variable_dictionary

         MEASURE                                          Data Item
1201     EQUIV_2  Median equivalised total household income (wee...
1786     ERP_P_2                             Persons aged 0-4 years
718     ERP_P_20                      Estimated resident population
8338     ERP_P_3                             Persons aged 5-9 years
784      ERP_P_4                           Persons aged 10-14 years
8415    HHTYPE_5                                   Total households
825     HHTYPE_6            Average household size (no. of persons)
3144   INCOME_17  Median total income (excl. Government pensions...
1950   INCOME_18  Total income (excl. Government pensions and al...
1954   INCOME_19  Total income earners (excl. Government pension...
1986    INCOME_3                         Total employee income ($m)
11650  INCOME_36  Mean total income (excl. Government pensions a...
3161   INCOME_37  Total income (excl. Government pensions and al...
2014   INCOME_41  Total income (excl. Government pensions and al...
921     INCOME_6      Total own unincorporated business income ($m)
7381    INCOME_9                       Total investment income ($m)

### 4.2.1) Check whether all selected variables are available in LGA data

In [22]:
available_lga_measures = set(lga_vars["MEASURE"])
missing_lga_measures = [m for m in selected_measures if m not in available_lga_measures]

print("Missing selected LGA measures:", missing_lga_measures)

Missing selected LGA measures: []

### 4.2.2) Inspect LGA sample rows

In [23]:
sample_lga = df_lga[
    (df_lga["REGIONTYPE"] == "LGA2021") &
    (df_lga["MEASURE"].isin(selected_measures))
].copy()

sample_lga.head(20)

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,MEASURE,Data Item,REGIONTYPE,Region Type,LGA_2021,Region,...,OBS_VALUE,Observation Value,UNIT_MEASURE,Unit of Measure,UNIT_MULT,Unit of Multiplier,OBS_STATUS,Observation Status,OBS_COMMENT,Observation Comment
718,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_20,Estimated resident population,LGA2021,Local Government Areas (2021),57770,Shark Bay,...,963.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
719,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_20,Estimated resident population,LGA2021,Local Government Areas (2021),57770,Shark Bay,...,962.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
720,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_20,Estimated resident population,LGA2021,Local Government Areas (2021),57770,Shark Bay,...,987.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
721,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_20,Estimated resident population,LGA2021,Local Government Areas (2021),57770,Shark Bay,...,1003.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
722,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_20,Estimated resident population,LGA2021,Local Government Areas (2021),57770,Shark Bay,...,1044.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
723,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_20,Estimated resident population,LGA2021,Local Government Areas (2021),57770,Shark Bay,...,1069.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
724,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_20,Estimated resident population,LGA2021,Local Government Areas (2021),70700,Coomalie,...,1412.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
725,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_20,Estimated resident population,LGA2021,Local Government Areas (2021),70700,Coomalie,...,1433.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
726,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_20,Estimated resident population,LGA2021,Local Government Areas (2021),70700,Coomalie,...,1421.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
727,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_20,Estimated resident population,LGA2021,Local Government Areas (2021),70700,Coomalie,...,1415.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
728,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_20,Estimated resident population,LGA2021,Local Government Areas (2021),70700,Coomalie,...,1414.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
729,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_20,Estimated resident population,LGA2021,Local Government Areas (2021),70700,Coomalie,...,1403.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
784,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_4,Persons aged 10-14 years,LGA2021,Local Government Areas (2021),37300,Weipa,...,314.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
785,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_4,Persons aged 10-14 years,LGA2021,Local Government Areas (2021),37300,Weipa,...,315.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
786,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_4,Persons aged 10-14 years,LGA2021,Local Government Areas (2021),37300,Weipa,...,326.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
787,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_4,Persons aged 10-14 years,LGA2021,Local Government Areas (2021),37300,Weipa,...,329.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
788,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_4,Persons aged 10-14 years,LGA2021,Local Government Areas (2021),37300,Weipa,...,331.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
789,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_4,Persons aged 10-14 years,LGA2021,Local Government Areas (2021),37300,Weipa,...,324.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
790,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_4,Persons aged 10-14 years,LGA2021,Local Government Areas (2021),43080,Karoonda East Murray,...,76.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN
791,DATAFLOW,ABS:ABS_REGIONAL_LGA2021(1.0.0),"Data by region 2011-2022, by LGA (ASGS Ed. 3, ...",I,ERP_P_4,Persons aged 10-14 years,LGA2021,Local Government Areas (2021),43080,Karoonda East Murray,...,77.0,NaN,PSNS,Persons,NaN,NaN,NaN,NaN,NaN,NaN

## 5) Summary table of selected variables

In [24]:
summary_selected_vars = pd.DataFrame({
    "measure": selected_measures
}).merge(
    asgs_vars.rename(columns={"MEASURE": "measure", "Data Item": "data_item"}),
    on="measure",
    how="left"
)

summary_selected_vars

      measure                                          data_item
0     ERP_P_2                             Persons aged 0-4 years
1     ERP_P_3                             Persons aged 5-9 years
2     ERP_P_4                           Persons aged 10-14 years
3    ERP_P_20                      Estimated resident population
4    HHTYPE_5                                   Total households
5    HHTYPE_6            Average household size (no. of persons)
6    INCOME_3                         Total employee income ($m)
7    INCOME_6      Total own unincorporated business income ($m)
8    INCOME_9                       Total investment income ($m)
9   INCOME_19  Total income earners (excl. Government pension...
10  INCOME_18  Total income (excl. Government pensions and al...
11  INCOME_17  Median total income (excl. Government pensions...
12  INCOME_36  Mean total income (excl. Government pensions a...
13    EQUIV_2  Median equivalised total household income (wee...
14  INCOME_41  Total income (excl. Government pensions and al...
15  INCOME_37  Total income (excl. Government pensions and al...

## Notebook summary

### Summary

- The ABS ASGS dataset contains income, population, household, and inequality variables across AUS, STE, SA4, SA3, and SA2 geographies.
- The ABS LGA dataset contains comparable variables for LGA2021 geographies.
- These variables can be mapped into standardized indicator names and used to construct derived income indicators, including income per person, income per household, and equivalised income measures.
- The SA2 code structure can be used to identify parent geographies such as State/Territory, SA4, and SA3.